#pragma once
#include <Windows.h>

#define MAX_LOADSTRING 100

//Main Window
#define MAIN_WINDOW_POSITION_WIDTH 820
#define MAIN_WINDOW_POSITION_HEIGHT 580

//Nickname registration window
#define NICK_REGISTRATION_WINDOW_WIDTH 380
#define NICK_REGISTRATION_WINDOW_HEIGHT 240

//Description nicknames' filed
#define DESCRIPT_NICK_FIELD_POS_X 10
#define DESCRIPT_NICK_FIELD_POS_Y 30
#define DESCRIPT_NICK_FIELD_POS_WIDTH 220
#define DESCRIPT_NICK_FIELD_POS_HEIGHT 30

//Input nickname field
#define INPUT_NICK_FIELD_POS_X 10
#define INPUT_NICK_FIELD_POS_Y 70
#define INPUT_NICK_FIELD_POS_WIDTH 270
#define INPUT_NICK_FIELD_POS_HEIGHT 30

#define NICK_BUTTON_CONTINUE_POS_X 80
#define NICK_BUTTON_CONTINUE_POS_Y 140
#define NICK_BUTTON_CONTINUE_POS_WIDTH 140
#define NICK_BUTTON_CONTINUE_POS_HEIGHT 35

//Registration Window
#define REGISTRATION_WINDOW_WIDTH 410
#define REGISTRATION_WINDOW_HEIGHT 270

#define ADDITIONAL_INFO_WIDTH 450
#define ADDITIONAL_INFO_HEIGHT 230

//Phone for the registration
#define REGISTRATION_PHONE_FIELD_POS_X 10
#define REGISTRATION_PHONE_FIELD_POS_Y 40
#define REGISTRATION_PHONE_FIELD_POS_WIDTH 182
#define REGISTRATION_PHONE_FIELD_POS_HEIGHT 26

//Registration email data
#define REGISTRATION_EMAIL_DATA_POS_X 10
#define REGISTRATION_EMAIL_DATA_POS_Y 110
#define REGISTRATION_EMAIL_DATA_WIDTH 170
#define REGISTRATION_EMAIL_DATA_HEIGHTS 26

//Description E-Mail field
#define DESCRIPT_EMAIL_AS_EXTRA_INFO_POS_X 20
#define DESCRIPT_EMAIL_AS_EXTRA_INFO_POS_Y 30
#define DESCRIPT_EMAIL_AS_EXTRA_INFO_POS_WIDTH 390
#define DESCRIPT_EMAIL_AS_EXTRA_INFO_POS_HEIGHT 60

//E-Mail input field
#define EMAIL_INPUT_FIELD_POS_X 20
#define EMAIL_INPUT_FIELD_POS_Y 90
#define EMAIL_INPUT_FIELD_POS_WIDTH 390
#define EMAIL_INPUT_FIELD_POS_HEIGHT 30

//An E-Mail window with a skip button
#define EMAIL_SKIP_BUTTON_POS_X 160
#define EMAIL_SKIP_BUTTON_POS_Y 140
#define EMAIL_SKIP_BUTTON_POS_WIDTH 140
#define EMAIL_SKIP_BUTTON_POS_HEIGHT 30

//Registration bt phone a button
#define REGISTRATION_BY_PHONE_POS_X 160
#define REGISTRATION_BY_PHONE_POS_Y 160
#define REGISTRATION_BY_PHONE_POS_WIDTH 210
#define REGISTRATION_BY_PHONE_POS_HEIGHT 40

//An E-Mail window with a access button
#define EMAIL_ACCESS_BUTTON_POS_X 310
#define EMAIL_ACCESS_BUTTON_POS_Y 140
#define EMAIL_ACCESS_BUTTON_POS_WIDTH 100
#define EMAIL_ACCESS_BUTTON_POS_HEIGHT 30

//Input Registered phone data
#define INPUT_REGISTERED_PHONE_POS_X 10
#define INPUT_REGISTERED_PHONE_POS_Y 68
#define INPUT_REGISTERED_PHONE_POS_WIDTH 360
#define INPUT_REGISTERED_PHONE_POS_HEIGHT 32

//Font registration Window
#define FONT_THE_REGISTRATION_WINDOW 28

//Log in the system
#define	LOG_IN_TO_REGISTER_POX_X 270
#define	LOG_IN_TO_REGISTER_POX_Y 190
#define	LOG_IN_TO_REGISTER_POX_WIDTH 90
#define	LOG_IN_TO_REGISTER_POX_HEIGHT 30

//About program
#define INFO_ABOUT_PROGRAM_WIDTH 470
#define INFO_ABOUT_PROGRAM_HEIGHT 230
#define ABOUT_AUTHOR_FIELD_POX_X 10
#define AUTHOR_FIELD_POS_Y 20
#define ABOUT_VERSION_FIELD_POX_Y 90
#define ABOUT_AUTHOR_FIELD_WIDTH 60
#define ABOUT_AUTHOR_FIELD_HEIGHT 40

//About author button close
#define ABOUT_BUTTON_CLOSE_POS_X 320
#define ABOUT_BUTTON_CLOSE_POS_Y 150
#define ABOUT_BUTTON_CLOSE_POS_WIDTH 70
#define ABOUT_BUTTON_CLOSE_POS_HEIGHT 20

//Author list
#define AUTHOR_LIST_POS_X 70
#define AUTHOR_LIST_POS_Y 20
#define AUTHOR_LIST_POS_WIDTH 360
#define AUTHOR_LIST_POS_HEIGHT 60

//Message field
#define MES_FIELD_X 260
#define MES_FIELD_Y 450
#define MES_FIELD_WIDTH 520
#define MES_FIELD_HEIGHT 20
#define INFO_FIELD_POS_X 260
#define INFO_FIELD_POS_Y 10
#define INFO_FIELD_WIDTH 520
#define INFO_FIELD_HEIGT 440

//Main list users
#define MAIN_LIST_USERS_POS_X 10
#define MAIN_LIST_USERS_POS_Y 12
#define MAIN_LIST_USERS_WIDTH 235
#define MAIN_LIST_USERS_HEIGHT 440
#define LIST_ADDED_USERS_POS_X 10
#define LIST_ADDED_USERS_POS_Y 10
#define LIST_ADDED_USERS_WIDTH 270
#define LIST_ADDED_USERS_HEIGHT 280
#define SEND_MES_WINDOW_X 260
#define SEND_MES_WINDOW_Y 480
#define SEND_MES_WINDOW_WIDTH 100
#define SEND_MES_WINDOW_HEIGHT 20
#define MAIN_FIELD_WIDTH 270
#define MAIN_FIELD_HEIGHT 300
#define DESCRIPT_FIELD_POS_X 20
#define DESCRIPT_FIELD_MOD_LAST_POS_Y 20
#define DESCRIPT_FIELD_MOD_POS_Y(x) x+30
#define DESCRIPT_FIELD_WIDTH 100
#define DESCRIPT_FIELD_HEIGHT 150
#define DESCRIPT_FIELD_MOD_HEIGHT 20 
#define INPUT_FIELD_POS_X 100
#define COUNT_FIELD_POS_X(x) x+30
//Синтаксис псевдо функции через добавить define
#define INPUT_FIELD_WIDTH 140
#define INPUT_FIELD_HEIGHT 20

//Adding user entry
//Accept the adding entry
#define ACCEPT_BUTTON_POS_X 100
#define ACCEPT_BUTTON_POS_Y 200
#define ACCEPT_BUTTON_WIDTH 45
#define ACCEPT_BUTTON_HEIGHT 20

//Cancel the adding entry
#define CANCEL_ADDING_ENTRY_POS_X 160
#define CANCEL_ADDING_ENTRY_POS_Y 200
#define CANCEL_ADDING_ENTRY_WIDTH 70
#define CANCEL_ADDING_ENTRY_HEIGHT 20

#define ADD_BUTTON_POS_X 20
#define ADD_BUTTON_POS_Y 295
#define MODIFY_BUTTON_POS_X 110
#define MODIFY_BUTTON_POS_Y 295
#define DELETE_BUTTON_POS_X 20
#define MAIN_CANCEL_BUTTON_POS_X 110
#define SELECTION_MENU_FIELD_POS_X 360
#define SELECTION_MENU_FIELD_POS_Y 400

//For some buttons
#define BUTTON_POS_Y 320
#define BUTTON_WIDTH 80
#define BUTTON_HEIGHT 20

//Modify Window
#define MODIFY_CLASS_WIDTH 260
#define MODIFY_CLASS_HEIGHT 300
#define MODIFY_BUTTON_EDIT_POS_X 100
#define MODIFY_BUTTON_EDIT_POS_Y(x) x+30

//Accept modification
#define MOD_ACCEPT_BUTTON_POS_X 80
#define MOD_ACCEPT_BUTTON_WIDTH 60

//Cancel moidification
#define MOD_CANCEL_BUTTON_POS_X 150
#define MOD_CANCEL_BUTTON_POS_Y 200
#define MOD_CANCEL_BUTTON_WIDTH 60
#define MOD_CANCEL_BUTTON_HEIGHT 20